### ISSUE TITLE
Error: Cannot find module 'parcel-bundler/src/packagers/JSPackager.js'

### ISSUE THREAD

**Issue by towry** [lc60005457/parcel-plugin-vue#8]
```
Server running at http://localhost:1234
🚨  Cannot find module 'parcel-bundler/src/assets/JSAsset'
Error: Cannot find module 'parcel-bundler/src/packagers/JSPackager.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (/Users/towry/.nvm/versions/node/v8.9.3/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/towry/workspace/nodenv/abc/node_modules/parcel-plugin-vue/src/VueAsset.js:3:17)
    at Module._compile (/Users/towry/.nvm/versions/node/v8.9.3/lib/node_modules/parcel-bundler/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by BoltDoggy** [comment]
@towry 
Do you installed the local  'parcel-bundler'?

> You Should install parcel-bundler yourself
> The plugins for parcel-bundler need a same version of parcel-bundler at runtime.

**Comment by BoltDoggy** [comment]
@towry I haven't received your reply for too long, I will close this issue.
